// Generated from comfrt.com/products.json via Shopify API
// To regenerate: curl 'https://comfrt.com/products.json?limit=250' \
//   -H 'User-Agent: Mozilla/5.0...' -o products.json && python3 scripts/extract-comfrt-products.py

export const COMFRT_PRODUCTS = [
    "Affirmation Hoodie",
    "Affirmation Straight Leg Sweatpants",
    "Affirmation Zip Hoodie",
    "Airplane Mode Travel Hoodie",
    "Airplane Mode Travel Sweatpants",
    "Airplane Mode Travel Zip Hoodie",
    "AllDayJersey™ Hoodie",
    "AllDayJersey™ Jogger",
    "AllDayJersey™ Straight Leg Pants",
    "AllDay Jersey Ankle-Length Jogger",
    "AllDay Jersey Hoodie",
    "Basic Crop Crew",
    "Basic Crop Hoodie",
    "Basic Crop Zip Hoodie",
    "Basic Fleece Short",
    "Basic Heavyweight Boxy Tee",
    "Basic Lightweight Tee",
    "Basic Lightweight Tee 3-Pack",
    "Basic Mock Neck Sweatshirt",
    "Basic Quarter Zip Mock Neck",
    "Basic Wide Leg Sweatpants",
    "Camo Crew",
    "Camo Crop Zip Hoodie",
    "Camo Hoodie",
    "Camo Kids Hoodie",
    "Camo Kids Sweatpants",
    "Camo Paw Hoodie",
    "Camo Shorts",
    "Camo Straight Leg Sweatpants",
    "Camo Sweatpants",
    "Camo Tee",
    "Camo Zip Hoodie",
    "Cloud Kids Sweatpants",
    "Cloud Lounge Long Sleeve Tee",
    "Cloud Lounge Pants",
    "Cloud Lounge Shorts",
    "Cloud Lounge Tee",
    "Cloud Sweatpants",
    "Cloud Sweatpants (Farewell)",
    "Cloud Zip Hoodie",
    "Cloud Zip Hoodie (Farewell)",
    "Cloud Zip Kids Hoodie",
    "Comfrt x We're Not Really Strangers Hoodie",
    "Comfrt x We're Not Really Strangers Sweatpants",
    "Comfrt x tarte Airplane Mode Travel Hoodie",
    "Comfrt x tarte Airplane Mode Travel Sweatpants",
    "ComfrtCore™ 5\" Biker Shorts",
    "ComfrtCore™ Double Layer Crop Tank",
    "ComfrtCore™ High-Waist Leggings",
    "ComfrtCore™ Strappy Crop Tank",
    "ComfrtCore™ V-Neck Crop Tank",
    "Coordinate Hoodie (Farewell)",
    "Coordinate Paw Hoodie",
    "Coordinate Sweatpants (Farewell)",
    "Essential Oversized Tee",
    "Halo Lightweight Crop Crew",
    "Halo Lightweight Crop Hoodie",
    "Halo Lightweight Straight Leg Sweatpants",
    "Love Hoodie",
    "Love Straight Leg Sweatpants",
    "Minimalist Crew",
    "Minimalist Hoodie",
    "Minimalist Hoodie (Farewell)",
    "Minimalist Kids Crew",
    "Minimalist Kids Hoodie",
    "Minimalist Kids Shorts",
    "Minimalist Kids Sweatpants",
    "Minimalist Paw Hoodie",
    "Minimalist Shorts",
    "Minimalist Straight Leg Sweatpants",
    "Minimalist Sweatpants",
    "Minimalist Sweatpants (Farewell)",
    "Minimalist Zip Hoodie",
    "Pastel Crew",
    "Pastel Hoodie",
    "Pastel Hoodie Pre-Order",
    "Pastel Kids Crew",
    "Pastel Kids Hoodie",
    "Pastel Kids Shorts",
    "Pastel Kids Sweatpants",
    "Pastel Paw Hoodie",
    "Pastel Shorts",
    "Pastel Straight Leg Sweatpants",
    "Pastel Sweatpants",
    "Pastel Sweatpants Pre-Order",
    "Pastel Zip Hoodie",
    "Puffer Jacket",
    "Rib Contour Boxer",
    "Rib Contour Crop Tank",
    "Rib Contour High Neck Tank",
    "Rib Contour Waist Length Tank",
    "Signature Crew",
    "Signature Hoodie",
    "Signature Hoodie (Farewell)",
    "Signature Kids Crew",
    "Signature Kids Hoodie",
    "Signature Kids Sweatpants",
    "Signature Paw Hoodie",
    "Signature Straight Leg Sweatpants",
    "Signature Sweatpants",
    "Signature Sweatpants (Farewell)",
    "Standard Hoodie",
    "Standard Hoodie (Farewell)",
    "Standard Kids Hoodie",
    "Standard Kids Sweatpants",
    "Standard Paw Hoodie",
    "Standard Sweatpants",
    "Standard Sweatpants (Farewell)",
    "Sweater Knit Hoodie",
    "Sweater Knit Jogger",
    "Tranquil Hoodie (Farewell)",
    "Tranquil Hoodie",
    "Tranquil Kids Hoodie",
    "Tranquil Kids Sweatpants",
    "Tranquil Paw Hoodie",
    "Tranquil Shorts",
    "Tranquil Sweatpants",
    "Travel Essentials Hoodie (Farewell)",
    "Travel Essentials Hoodie",
    "Travel Essentials Kids Hoodie",
    "Travel Essentials Kids Sweatpants",
    "Travel Essentials Sweatpants",
    "Travel Essentials Sweatpants (Farewell)",
    "Travel Essentials Zip Hoodie",
    "Waffle Kids Lounge Long Sleeve",
    "Waffle Kids Lounge Pant",
    "Waffle Lounge 7\" Short",
    "Waffle Lounge Jogger",
    "Waffle Lounge Long Sleeve",
    "Waffle Lounge Pant",
    "Waffle Lounge Short",
    "Waffle Lounge Tee",
    "Weighted Hoodie",
    "Weighted Kids Hoodie",
    "You Matter Hoodie",
    "You Matter Paw Hoodie",
    "You Matter Straight Leg Sweatpants",
]

export const COMFRT_COLORS = [
    "Adirondack",
    "Allure",
    "Almond",
    "Aloe",
    "Alpine",
    "Aqua",
    "Ash",
    "Ash Tiger",
    "Astro",
    "Azure Blue",
    "Baby Blue",
    "Baby Pink",
    "Bark",
    "Bear",
    "Berry",
    "Black",
    "Blackberry",
    "Blue Steel",
    "Blue Willow",
    "Bone",
    "Brown Leopard",
    "Bubblegum",
    "Buffalo Plaid",
    "Butter",
    "Buttercream",
    "Canary",
    "Cappuccino",
    "Cement",
    "Charcoal",
    "Charcoal Black",
    "Cherry",
    "Cherry Blossom",
    "Chocolate",
    "Cloud Grey",
    "Cloud Nine",
    "Cloud White",
    "Cobalt Blue",
    "Cocoa",
    "Coconut",
    "Cookies & Cream",
    "Coral",
    "Coral Blush",
    "Cotton",
    "Cotton Candy",
    "Creamsicle",
    "Crimson",
    "Dark Grey",
    "Desert",
    "Desert Leopard",
    "Dove",
    "Driftwood",
    "Dune",
    "Dust",
    "Dusty Pine",
    "Electric Blue",
    "Espresso",
    "Evergreen",
    "Fawn",
    "Fog",
    "Forest",
    "French Vanilla",
    "Frost",
    "Glacier",
    "Graphite",
    "Green Tea",
    "Heart Print",
    "Hibiscus Red",
    "High Sierra",
    "Holly Red Fairisle",
    "Honeydew",
    "Hot Pink",
    "Hunter",
    "Indigo",
    "Iris",
    "Ivory",
    "Jade",
    "Jet Black",
    "Latte",
    "Lavender",
    "Lavender Cloud",
    "Light Heather Grey",
    "Lilac",
    "Lilac Blush",
    "Lt Heather Grey",
    "Maroon",
    "Mauve",
    "Medium Heather Grey",
    "Midnight",
    "Midnight Blue",
    "Midnight Forest",
    "Millstone Green",
    "Mineral",
    "Mint",
    "Mist",
    "Mocha",
    "Moonlight",
    "Moonstone",
    "Moss",
    "Mountain Moss",
    "Navy",
    "Oat",
    "Obsidian",
    "Ocean",
    "Olive",
    "Onyx",
    "Onyx Black",
    "Opal",
    "Orchid",
    "Pacific",
    "Pale Mint",
    "Pale Rose",
    "Panther",
    "Paris Blue",
    "Pastel",
    "Peach",
    "Peony",
    "Periwinkle",
    "Petal",
    "Petal Pink Oak",
    "Pine",
    "Pink Rose",
    "Pixie",
    "Plum",
    "Powder",
    "Powder Blue",
    "Powder Pink",
    "Rainbow",
    "Raspberry",
    "Raven",
    "Red Velvet",
    "Rose Quartz",
    "Sage Green",
    "Sand",
    "Sea Glass",
    "Seafoam",
    "Shell",
    "Silver Birch",
    "Sky",
    "Skylight",
    "Slate",
    "Slate Grey",
    "Snow",
    "Snow Leopard",
    "Snow Sprinkle",
    "Snowflake",
    "Sorbet",
    "Steel",
    "Steel Grey",
    "Stone",
    "Stone Blue",
    "Storm",
    "Strawberry Swirl",
    "Sunset",
    "Teal",
    "Teddy",
    "Thunder",
    "Timber",
    "Tinsel Tree",
    "Truffle",
    "Twilight",
    "Violet",
    "Walnut",
    "Wasabi",
    "Wave",
    "White Dove",
    "White Oak",
    "Wild Berry",
    "Wine",
    "Wolf Grey",
    "Woodland",
]
